language: generic 
sudo: required
services:
    - docker

before install:
    -  docker build -t maxlaycock70/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true maxlaycock70/docker-react npm run test